# -*- coding: utf-8 -*-
"""data_utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ugJ7ZjPVejpn5hSKUFtLmpCn0KDjjDGc

#Installing Dependencies
"""

!pip -q install dataset transformers accelerate peft trl bitsandbytes

#Imports
import os
import google.colab
import huggingface_hub
from huggingface_hub import login
from google.colab import userdata

hf_token = userdata.get("HF_TOKEN")

print("Token loaded successfully!" if hf_token else "Token not found.")

if hf_token:
    os.environ["HF_TOKEN"] = hf_token

#====================
#Loading Dataset
#====================

from datasets import load_dataset

dataset = load_dataset(
    "text",
    data_files = "/content/medical_assistant_dataset.txt"

)

dataset = dataset["train"]
print(f"Loaded dataset with {len(dataset)} samples.")

# ==============================================
# Format dataset into instruction-response style
# ==============================================

def format_prompt(example_text):
    """
    Prompt that incorporates intent and difficulty to help the model
    learn specialized medical response styles.
    """
    prompt = f"""### Instruction:
You are a professional medical assistant. Provide a response that is appropriate for the following intent and difficulty level.

### Metadata:
- Intent: {example_text.get('intent', 'General medical inquiry')}
- Difficulty: {example_text.get('difficulty', 'Basic')}

### Input:
User: {example_text.get('user_query', example_text.get('text', ''))}

### Response:
Assistant: {example_text.get('assistant_response', 'N/A')}
"""
    return {"text": prompt}


# ==============================================
# Apply format_prompt function to the dataset
# ==============================================

dataset = dataset.map(format_prompt)
print("Dataset formatted successfully!")

print("Sample Data: ")
print(dataset[0])